apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: witself-db
  namespace: witself
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws
  target:
    name: witself-db
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: aws-sandbox-usw2-dev/db
