package gitopsvalues

import (
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"

	"go.yaml.in/yaml/v3"
)

// BackupImagePins selects the build-time provisioned PostgreSQL backup image.
// The legacy scalar form remains supported for existing runtime-install images.
type BackupImagePins struct {
	Repository string
	Tag        string
	Digest     string
	legacy     string
}

var backupRepositoryPattern = regexp.MustCompile(`^([a-z0-9]+([.-][a-z0-9]+)*(:[0-9]+)?/)?[a-z0-9]+(([._]|__|-+)[a-z0-9]+)*(/[a-z0-9]+(([._]|__|-+)[a-z0-9]+)*)*$`)
var backupTagPattern = regexp.MustCompile(`^[A-Za-z0-9_][A-Za-z0-9_.-]{0,127}$`)

func (p BackupImagePins) validate() error {
	if p.Repository == "" && p.Tag == "" && p.Digest == "" {
		return nil
	}
	if !backupRepositoryPattern.MatchString(p.Repository) || !backupTagPattern.MatchString(p.Tag) {
		return fmt.Errorf("apps.civoPostgres.backup.image requires a valid repository and tag")
	}
	if p.Digest != "" && !imageDigestPattern.MatchString(p.Digest) {
		return fmt.Errorf("apps.civoPostgres.backup.image.digest must be empty or sha256 followed by 64 lowercase hexadecimal characters")
	}
	return nil
}

func readBackupImagePins(path string) (*BackupImagePins, error) {
	body, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	pins, err := parseBackupImagePins(body)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", path, err)
	}
	return pins, nil
}

func parseBackupImagePins(body []byte) (*BackupImagePins, error) {
	var doc struct {
		Apps struct {
			CivoPostgres struct {
				Backup struct {
					Image yaml.Node `yaml:"image"`
				} `yaml:"backup"`
			} `yaml:"civoPostgres"`
		} `yaml:"apps"`
	}
	if err := yaml.Unmarshal(body, &doc); err != nil {
		return nil, fmt.Errorf("parse cell values: %w", err)
	}
	node := doc.Apps.CivoPostgres.Backup.Image
	if node.Kind == 0 {
		return nil, nil
	}
	if node.Kind == yaml.ScalarNode && node.Tag == "!!str" {
		if node.Value == "" {
			return nil, fmt.Errorf("apps.civoPostgres.backup.image legacy string must not be empty")
		}
		return &BackupImagePins{legacy: node.Value}, nil
	}
	if node.Kind != yaml.MappingNode {
		return nil, fmt.Errorf("apps.civoPostgres.backup.image must be a string or image pin object")
	}
	pins := &BackupImagePins{}
	fields := map[string]*string{"repository": &pins.Repository, "tag": &pins.Tag, "digest": &pins.Digest}
	for i := 0; i+1 < len(node.Content); i += 2 {
		key, value := node.Content[i], node.Content[i+1]
		field, ok := fields[key.Value]
		if !ok {
			return nil, fmt.Errorf("apps.civoPostgres.backup.image contains an unknown or duplicate field")
		}
		if value.Kind != yaml.ScalarNode || value.Tag != "!!str" {
			return nil, fmt.Errorf("apps.civoPostgres.backup.image.%s must be a string", key.Value)
		}
		*field = value.Value
		delete(fields, key.Value)
	}
	if err := pins.validate(); err != nil {
		return nil, err
	}
	if pins.Repository == "" {
		return nil, nil
	}
	return pins, nil
}

// addBackupImagePins inserts only the optional pin after backup.enabled. It
// leaves the frozen cell templates and every unrelated generated byte intact.
func addBackupImagePins(body []byte, pins *BackupImagePins) ([]byte, error) {
	if pins == nil {
		return body, nil
	}
	if err := pins.validate(); err != nil {
		return nil, err
	}
	var doc yaml.Node
	if err := yaml.Unmarshal(body, &doc); err != nil {
		return nil, fmt.Errorf("parse generated cell values: %w", err)
	}
	if len(doc.Content) != 1 {
		return nil, fmt.Errorf("generated cell values must contain one YAML document")
	}
	node := doc.Content[0]
	for _, key := range []string{"apps", "civoPostgres", "backup", "enabled"} {
		var next *yaml.Node
		if node.Kind == yaml.MappingNode {
			for i := 0; i+1 < len(node.Content); i += 2 {
				if node.Content[i].Value == key {
					next = node.Content[i+1]
					break
				}
			}
		}
		if next == nil {
			return nil, fmt.Errorf("generated cell values lack apps.civoPostgres.backup.enabled; cannot pin backup image")
		}
		node = next
	}
	lines := strings.SplitAfter(string(body), "\n")
	if node.Kind != yaml.ScalarNode || node.Style != 0 || node.Line < 1 || node.Line > len(lines) {
		return nil, fmt.Errorf("generated cell backup.enabled must be a plain scalar")
	}
	line := lines[node.Line-1]
	indent := line[:len(line)-len(strings.TrimLeft(line, " "))]
	var addition string
	if pins.legacy != "" {
		addition = indent + "image: " + strconv.Quote(pins.legacy) + "\n"
	} else {
		addition = indent + "image:\n" + indent + "  repository: " + strconv.Quote(pins.Repository) + "\n" + indent + "  tag: " + strconv.Quote(pins.Tag) + "\n"
		if pins.Digest != "" {
			addition += indent + "  digest: " + pins.Digest + "\n"
		}
	}
	lines[node.Line-1] = line + addition
	return []byte(strings.Join(lines, "")), nil
}
