{{- $ingress := .Values.apps.witselfServer.gcpIngress -}}
{{- if and .Values.apps.witselfServer.enabled $ingress.enabled (eq .Values.cell.cloud "gcp") }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ default "witself-server" $ingress.backendConfigName | quote }}
  namespace: {{ .Values.apps.witselfServer.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
{{- toYaml $ingress.backendConfig | nindent 2 }}
{{- end }}
