{{- $secrets := .Values.apps.witselfServer.secrets -}}
{{- $dbEnabled := default true $secrets.database.enabled -}}
{{- if or .Values.apps.witselfServer.enabled $secrets.bootstrap.enabled $dbEnabled $secrets.provision.enabled }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.apps.witselfServer.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}
